In [112]:
import requests
import pandas as pd
import time
from dotenv import load_dotenv
import os
from sqlalchemy import create_engine, text
from fetch_fmp.py import fetch_data

ModuleNotFoundError: No module named 'fetch_fmp'

In [113]:
engine = create_engine("mysql+pymysql://root:Aatroxkalistartop123@localhost:3306/finance_db")

In [81]:
load_dotenv()
api_key = os.getenv('FMP_api')

In [82]:
# load all lists
stock_list    = pd.read_csv("stock_list.csv")
active        = pd.read_csv("active_trading.csv")
etf_list      = pd.read_csv("ETF_list.csv")
fin_list      = pd.read_csv("financial_statement_list.csv")

symbols = active["symbol"].tolist()

etf_symbols = etf_list["symbol"].tolist()
symbols = [s for s in symbols if s not in etf_symbols]

fin_symbols = fin_list["symbol"].tolist()
symbols = [s for s in symbols if s in fin_symbols]

In [106]:
fetch_data("https://financialmodelingprep.com/stable/ratios?symbol=NVDA&apikey=o9NfoSRmyQfE5ipiaKS7jku9n5C6G1dV")

,symbol,date,fiscalYear,period,reportedCurrency,grossProfitMargin,ebitMargin,ebitdaMargin,operatingProfitMargin,pretaxProfitMargin,...,operatingCashFlowPerShare,capexPerShare,freeCashFlowPerShare,netIncomePerEBT,ebtPerEbit,priceToFairValue,debtToMarketCap,effectiveTaxRate,enterpriseValueMultiple,dividendPerShare
0,NVDA,2026-01-25,2026,FY,USD,0.710681,0.656249,0.669414,0.603817,0.655049,...,4.226382,0.248601,3.977781,0.848830,1.084847,28.812260,0.001869,0.151170,31.357393,0.040076
1,NVDA,2025-01-26,2025,FY,USD,0.749887,0.645785,0.660069,0.624175,0.643892,...,2.610018,0.131786,2.478233,0.867351,1.031589,36.655907,0.002910,0.132649,33.777402,0.033965
2,NVDA,2024-01-28,2024,FY,USD,0.727176,0.559322,0.584075,0.541217,0.555103,...,1.137708,0.043297,1.094411,0.880005,1.025658,35.887764,0.006295,0.119995,43.452219,0.015998
3,NVDA,2023-01-29,2023,FY,USD,0.569289,0.164714,0.221917,0.156595,0.155001,...,0.226819,0.073703,0.153116,1.044726,0.989820,21.560527,0.022986,-0.044726,81.047645,0.016003
4,NVDA,2022-01-30,2022,FY,USD,0.649290,0.378130,0.421751,0.373077,0.369362,...,0.364904,0.039103,0.325801,0.980988,0.990041,22.969728,0.017907,0.019012,54.718650,0.015986

In [107]:
fetch_data("https://financialmodelingprep.com/stable/ratios-ttm?symbol=NVDA&apikey=o9NfoSRmyQfE5ipiaKS7jku9n5C6G1dV")

,symbol,grossProfitMarginTTM,ebitMarginTTM,ebitdaMarginTTM,operatingProfitMarginTTM,pretaxProfitMarginTTM,continuousOperationsProfitMarginTTM,netProfitMarginTTM,bottomLineProfitMarginTTM,receivablesTurnoverTTM,...,operatingCashFlowPerShareTTM,capexPerShareTTM,freeCashFlowPerShareTTM,netIncomePerEBTTTM,ebtPerEbitTTM,priceToFairValueTTM,debtToMarketCapTTM,effectiveTaxRateTTM,enterpriseValueMultipleTTM,dividendPerShareTTM
0,NVDA,0.710681,0.656249,0.669414,0.603817,0.655049,0.556025,0.556025,0.556025,5.613737,...,4.226382,0.248601,3.977781,0.84883,1.084847,26.720138,0.002015,0.15117,29.082064,0.04